#!/bin/bash

if [ $# -eq 0 ]; then
    echo "Usage:
./create-odoo-image <odoo version> <desired custom odoo image name>
Exiting ..."
    exit 1
fi

version="${1}"
imgname="${2}"

digest=
echo "Pulling version ${version} of Odoo ..."
out=$(docker pull odoo:${version})
# extracting digest from the log
while read -r line; do
    if [[ "${line}" =~ ^Digest.* ]] ; then
        digest="${line#*Digest: }"
    fi
done <<< "${out}"
echo "digest: ${digest}"

# build custom odoo image
docker build \
    --no-cache \
    -t "${imgname}" \
    --build-arg odoo_version="@${digest}" \
    .
