#!/bin/bash

# clearing intermediate images with name '<none>'

count=0
while read -r line; do
    echo "${line}"
    echo
    read -ra arr <<< "${line}"
    if [[ "${arr[0]}" == "<none>"* ]]; then
        echo "${arr}"
        echo "Deleting ${arr[2]} ..."
        docker rmi -f "${arr[2]}"
        ((count++))
    fi
done <<< "$(docker images)"
echo "Deleted ${count} 'none' images"
echo "Finished"
